name: Deploy Docs

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Job will be cancelled if it runs for more than 10 minutes
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
          cache-suffix: "docs"

      - name: Install dependencies
        run: |
          yarn
          uv sync --all-groups
      - name: Build llms-text
        run: make llms-text
      - name: Build site
        run: |
          DOWNLOAD_STATS=true make build-docs
        env:
          OPENAI_API_KEY: sf-proj-1234567890 # fake placeholder, shouldn't actually be used
          ANTHROPIC_API_KEY: sk-ant-api03-1234567890 # fake placeholder, shouldn't actually be used
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
